Her kan du finde alle info fra projeket

Du skal starte med at indstillere

du skal starte med at instillere pip.
pip er management system til at indstillere forskiligere python pakker på din pc

guide: https://phoenixnap.com/kb/install-pip-windows

du skal bruge en SpeechRecognition: https://pypi.org/project/SpeechRecognition/

du skal bruge pyttsx3: https://pypi.org/project/pyttsx3/
den kan godt giv problemer:https://stackoverflow.com/questions/60307452/pyttsx3-initialization-error-cant-use-pyttsx3

du skal bruge PyAudio: https://pypi.org/project/PyAudio/

du kan bruge Pywhatkit til at gå på YouTube osv. : https://pypi.org/project/pywhatkit/

du kan bruge wikipedia: https://pypi.org/project/wikipedia/



